### ISSUE TITLE
Uncommitted gtm track can't be displayed correctly

### ISSUE THREAD

**Issue by Korne127** [DEVELOPEST/gtm-core#64] opened 2021-05-22 02:53 UTC
I am in a situation where `gtm status` doesn't give a correct result. When I execute that command, a time between 5 and 20 minutes is displayed which doesn't change (after programming for over an hour).
I am not sure what has been causing this, however I could assume it is because I manually deleted .event files in the folder.

I started something, then stopped and deleted the existing .event files (there have only been 2 or 3, very few), then started again. The .event files are generated correctly, there are over 200 currently and the times seem correct.
However, using the gtm status command gets a weird time between 5 and 20 minutes (it changes back and forth). The same goes for the time displayed in IntelliJ.

If I create an empty folder and do `git init` and then `gtm init` and then use the gtm status command, a correct time of a bit above one hour appears.
![image](https://user-images.githubusercontent.com/33464213/119212297-bb5abe80-bab7-11eb-95b5-7d75971fcd5a.png)
I committed minor changes and `gtm report` delivers the same
![image](https://user-images.githubusercontent.com/33464213/119212343-f230d480-bab7-11eb-88e8-aad3983183aa.png)

However, if I copy the whole project and do `gtm init` and `gtm status`, the wrong time appears again:
![image](https://user-images.githubusercontent.com/33464213/119212403-518ee480-bab8-11eb-8dfa-e36432685cee.png)
Even if I do `gtm uninit` and `gtm init` again and copy the gtm folder in it, the same wrong time appears again.

I've tried deleting elements manually and adding them back but that doesn't solve anything, either.

And I tried committing it (in the whole copied project), but even `gtm report` after a commit gets the wrong time again (noticeably, it is one second different which I have no explanation for)
![image](https://user-images.githubusercontent.com/33464213/119212467-d2e67700-bab8-11eb-8c0c-a74b06a471ac.png)

What I noticed though is this weird number.

> [+12 -149 = -137] [590/hr]

I looked at my previous tracked commits and all but the last one had -0 (the last one -7).
I tried to find an explanation in the wiki and the original gtm wiki but nowhere it has been explained what these numbers mean.

Can you explain that to me? Maybe it has something to do with this behaviour.

Also, I've wondered what the generated application called "terminal" with a size of 0 Bytes is for. I didn't delete it but it seems weird being there beside all the .event files.

Thanks for reading and I hope you can help me with this :)

**Comment by kilpkonn** [comment] 2021-05-22 05:53
Hei, thanks for the very detailed report!

Deleting .event files causes a loss of time, so this is a expected behavior - these files shouldn't be manually modified.
The time displayed in IntelliJ is the same `gtm status` displays. (Well, if multiple IntelliJs are open they sometimes show wrong number, but that is purely UI).
The "weird line" is `[+added_lines -removed_lines = total_change_in_lines] lines/hr` if I understood your question correctly.
The .terminal is needed if you use terminal record plugin I believe. Not 100% sure as I haven't changed if from original gtm, but you shouldn't delete it either.

When you copied `.gtm` folder from one project to other, is the file structure the same?
If there are event files for say `src/a.txt` but there is only `src/b.txt` in git I believe the time is lost as well.

I'm thinking that maybe we should start using sqlite instead of `.event` files at some point as I'm afraid some users may also mess with `.event` files causing loss of data etc.

**Comment by Korne127** [comment] 2021-05-22 12:38
I know that deleting .event files causes a loss of time, I mean that was the reason why I did it.
But that doesn't explain this behaviour to me.
I describe it as I remember:

I created one new class which created one .event file. Then, I removed that class and deleted that one .event file which had that class name. Then I continued programming on other classes, creating new .event files.

As I've said, the .event files contain the right time, when I copy the folder to a new gtm project, the correct time (over an hour) is displayed.
But in the real project, and even a copied one, a time between 5 and 20 minutes is displayed which sometimes goes up, sometimes goes down, even back to one minute and ignores most of the .event files.

So the problem is **not** that the recorded time of the specific .event files I deleted is gone. That was completely expected and the reason why I deleted this _single_ file. The problem is that the complete time calculation of all the other recorded .event files doesn't work correctly, and I don't know why.

**Comment by Korne127** [comment] 2021-05-22 12:53
Another example is now that I've continued for around 10 minutes on it, and the IntelliJ time went up from 16 to 25 minutes as well. All the previous .event files are saved plus additional ones from the last ten minutes. When I do gtm status, however, it still displays the same 16m 22s

**Comment by kilpkonn** [comment] 2021-05-22 12:59
Ok, will look into this in few days. The time in IntelliJ should be the same as in status so this seems weird.

**Comment by Korne127** [comment] 2021-05-22 13:51
I mean, that's not the main problem haha. I think that is just a "symptom". That the time goes up as it should in IntelliJ but there is something weird happening that the time when I actively perform the command resets again or something.

I guess I'll try to if I find a way to reinitialise it in a way that this doesn't happen anymore, but considering this doesn't happen with a new project but does with a copied, I could imagine it has to do with some error in the git notes?

**Comment by kilpkonn** [comment] 2021-05-22 17:56
Hmm, `gtm status` only looks at the files inside `.gtm/` dir and should have nothing to do with the notes.
`gtm report` gits it's data only from the notes and does not read `.gtm/` dir event files.

Can't really think of a reason why the uncommitted time could change right now as there is no complex formula etc behind calculating it and the input should be straight forward as well.

Only thing that comes to my mind is that if file permissions change and `gtm` fails to read file due to it, but don't think they could change back etc.

EDIT: Actually 2 git repositories one in another could technically cause weird behavior as well, but I don't think that's the case

**Comment by Korne127** [comment] 2021-05-23 21:33
Well, but here you can see that if I just delete the git folder and reinitialise git and gtm, the problem disappears.
![image](https://user-images.githubusercontent.com/33464213/119277249-d5fb7780-bc1e-11eb-8d61-d724d53e183c.png)
The gtm folder is unchanged, so it definitely has something to do with the notes…

I tried replacing the git folder afterwards, but that just reintroduced the bug, so it definitely has to do with that one, I just really don't know what introduced it and how I can prevent that…

**Comment by kilpkonn** [comment] 2021-05-24 07:36
Ok, will look into this

**Comment by Korne127** [comment] 2021-05-24 10:22
If it helps, I can send you my project with the .git and .gtm folder because it's a weird bug and I'm not sure how easy it is to reproduce.

**Comment by Korne127** [comment] 2021-05-24 11:03
I FOUND A SOLUTION!
This is definitely the weirdest bug I have **ever** encountered.

To find a solution, I first cloned an old repo, then replaced the .git and .gtm folder. gtm status still worked correctly. When I replaced all source files to the current version, the mistake appeared again. So I got back to the previous version and replaced one file by one. I noticed that some changes were still added so I un-added them. After replacing one file by one, it still worked.

So… the only change were the added files in the git repository.
To check, I used the original project file (the tests were just in test copies) and performed `gtm status`. It gave that wrong bug. After performing `git add --all`, `git status` worked just fine :D

Here, look!
![image](https://user-images.githubusercontent.com/33464213/119338253-0f200000-bc90-11eb-96ff-5d8c8ac58128.png)

So I guess the mistake is in that some previous changes are committed and there are newer changes of the same file that aren't committed yet.

I'm really glad I could solve it like that, but it still is a really weird bug.

**Comment by kilpkonn** [comment] 2021-05-24 11:24
Good to hear!
So do I understand correctly, that you previously you were not tracking all of the files and time for files not tracked was skipped when showing `gtm status`?

**Comment by Korne127** [comment] 2021-05-26 21:41
Well, when you phrase it like that, I feel pretty stupid.
But yeah; I'm sorry for using your time.

I didn't notice that because
1. I didn't knew that I had added some files on git
2. I didn't realise it only shows the time of those added in the status command, especially because in a past commit it shows the time I spent on these in the report even although I didn't add them

Still, thank you very much for your effort to help :)

**Comment by kilpkonn** [comment] 2021-05-27 05:15
No need to feel bad, you got this sorted out on your own anyways :D 
I'll close this isssue as it seems solved and possibly add some QA section somewhere in the readme etc in the future as there are likely other people wondering over same stuff.

**Closed as completed** 2021-05-27 05:15 UTC
Labels: bug
